# -*- coding: utf-8 -*-
"""Gerando Senhas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x70Gl9sZUlzFXieNtu8e6hpnXDWhU9FG
"""

import random 

lower = ('abcdefghijklmnopqrstuvwxyz')
upper = ('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
numbers = '0123456789'
symbols = "[]{}()*;/,._-"

all = lower + upper + numbers + symbols

length = 16
password = "".join(random.sample(all, length))
print(password)